version: '3.8'

services:
  # Discovery Service
  discovery-service:
    build: ../../discovery-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Config Service
  config-service:
    build: ../../config-service
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - ecommerce-network
    restart: unless-stopped

  # API Gateway
  api-gateway:
    build: ../../api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
    depends_on:
      - discovery-service
      - config-service
    networks:
      - ecommerce-network
    restart: unless-stopped

  # User Service
  user-service:
    build: ../../user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - SPRING_DATASOURCE_URL=${USER_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Product Catalog Service
  product-catalog-service:
    build: ../../product-catalog-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - SPRING_DATASOURCE_URL=${PRODUCT_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_REDIS_HOST=${REDIS_HOST}
      - SPRING_REDIS_PORT=${REDIS_PORT}
      - SPRING_REDIS_PASSWORD=${REDIS_PASSWORD}
      - SPRING_ELASTICSEARCH_URIS=${ELASTICSEARCH_URL}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Order Service
  order-service:
    build: ../../order-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - SPRING_DATASOURCE_URL=${ORDER_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Payment Service
  payment-service:
    build: ../../payment-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - SPRING_DATASOURCE_URL=${PAYMENT_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
      - RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Email Service
  email-service:
    build: ../../email-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - SPRING_DATASOURCE_URL=${EMAIL_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - SPRING_MAIL_HOST=${MAIL_HOST}
      - SPRING_MAIL_PORT=${MAIL_PORT}
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Search Service
  search-service:
    build: ../../search-service
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=cloud
      - SPRING_ELASTICSEARCH_URIS=${ELASTICSEARCH_URL}
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - config-service
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge 